language: node_js
node_js:
  - node
dist: xenial
sudo: false
git:
  depth: false
branches:
  only:
    - develop
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: public
  repo: toastmasters-kosice/toastmasters-kosice.github.io
  target-branch: master
  verbose: true
  on:
    branch: develop
